### ISSUE TITLE
classcast exception in CommonProfile : cannot cast jsonArray to String 

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#1200]
Hello,

There might be some issue between CommonProfile and CommonProfileDefinition.

The username field (when parsed from an SAML2Response) is mapped into a JSONArray.
Indeed in the CommonProfileDefinition there is no rule regarding that attribute 

As a result the getUsername in CommonProfile fails with a ClassCastException.

Shouldn't there be a rule for username as well to keep consistency between the 2 classes ?

André

**Comment by leleuj** [comment]
In the `CommonProfile`,  the username is expected to be a `String`: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/CommonProfile.java#L75 which indeed may conflict with an attribute in the `SAML2Profile` which is a list.

I'm not sure to see the link the `JSONArray`:  can you paste the full stack trace? Thanks

**Comment by andre-doherty** [comment]
yes here it is : 

`
java.lang.ClassCastException: net.minidev.json.JSONArray cannot be cast to java.lang.String
	at org.pac4j.core.profile.CommonProfile.getUsername(CommonProfile.java:62) ~[pac4j-core-3.0.2.jar:na]
	at org.pac4j.core.profile.Pac4JPrincipal.<init>(Pac4JPrincipal.java:24) ~[pac4j-core-3.0.2.jar:na]
	at org.pac4j.core.profile.CommonProfile.asPrincipal(CommonProfile.java:116) ~[pac4j-core-3.0.2.jar:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_112]
	at org.pac4j.j2e.util.Pac4JHttpServletRequestWrapper.getPrincipal(Pac4JHttpServletRequestWrapper.java:39) ~[j2e-pac4j-4.0.0.jar:na]
	at org.pac4j.j2e.util.Pac4JHttpServletRequestWrapper.getUserPrincipal(Pac4JHttpServletRequestWrapper.java:44) ~[j2e-pac4j-4.0.0.jar:na]
	at javax.servlet.http.HttpServletRequestWrapper.getUserPrincipal(HttpServletRequestWrapper.java:225) ~[com.ibm.websphere.javaee.servlet.3.1_1.0.22.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.getUsernameForRequest(FrameworkServlet.java:1093) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.publishRequestHandledEvent(FrameworkServlet.java:1078) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[com.ibm.websphere.javaee.servlet.3.1_1.0.22.jar:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[com.ibm.websphere.javaee.servlet.3.1_1.0.22.jar:na]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255) ~[na:na]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743) ~[na:na]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440) ~[na:na]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182) [com.ibm.ws.webcontainer_1.1.22.jar:na]`

As a workaround i have to define a Custom ProfileDefinition such as  : 

`public class CustomProfileDefinition<P extends CommonProfile> extends CommonProfileDefinition<P> {

	public static final String USERNAME = "username";
	public static final String TELEPHONE_NUMBER = "telephoneNumber";

	public CustomProfileDefinition() {
		super();
		primary(USERNAME, Converters.STRING);
		primary(TELEPHONE_NUMBER, Converters.STRING);
	}
	
	public CustomProfileDefinition(final Function<Object[], P> profileFactory) {
        this();
        setProfileFactory(profileFactory);
    }

}`

Then the JSONArray are converted in String and the ClassCastException disappears

**Comment by leleuj** [comment]
OK. Indeed, I think there is a missing converter for the username. Would you mind submitting a PR for that? Thanks
