### ISSUE TITLE
NullPointer on KeycloakRolesAuthorizationGenerator

### ISSUE THREAD

**Issue by brunojcm** [pac4j/pac4j#1212]
I think there is a missing null check in the new `KeycloakRolesAuthorizationGenerator`, I'm getting a NullPointerException when there is no `realm_access` in the access token:

```
2018-12-07 03:56:19,727 WARN  [org.pac4j.oidc.authorization.generator.KeycloakRolesAuthorizationGenerator] (default task-2) Cannot parse Keycloak roles: java.lang.NullPointerException
	at org.pac4j.oidc.authorization.generator.KeycloakRolesAuthorizationGenerator.generate(KeycloakRolesAuthorizationGenerator.java:37)
	at org.pac4j.oidc.authorization.generator.KeycloakRolesAuthorizationGenerator.generate(KeycloakRolesAuthorizationGenerator.java:20)
	at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:98)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:92)
```

I believe `jwtClaimsSet.getJSONObjectClaim("realm_access")` can return null, so we need to also check it.

**Comment by leleuj** [comment]
It should be fixed now: https://github.com/pac4j/pac4j/commit/fae90bb5a79b432b533be809293e20e31e6e0111

**Comment by brunojcm** [comment]
Nice!! Thanks for the quick fix :)
