### ISSUE TITLE
LinkedIn login not working

### ISSUE THREAD

**Issue by veerachary-mymedicare** [pac4j/pac4j#1261]
We are using pac4j 3.5.0 with spring boot.
For Linked-in client it giving error:
final LinkedIn2Client linkedInClient = new LinkedIn2Client(linkedInClientId, linkedInSecret);
linkedInClient.setScope("r_basicprofile,r_emailaddress");

Would you please suggest, why Linked in login not working.

The error log is:
DEBUG o.p.o.p.c.OAuth20ProfileCreator - sendRequestForData.119:
				Request took: 885 ms for: https://api.linkedin.com/v1/people/~:(id,first-name,last-name,maiden-name,formatted-name,phonetic-first-name,phonetic-last-name,formatted-phonetic-name,headline,location,industry,current-share,num-connections,num-connections-capped,summary,specialties,positions,picture-url,site-standard-profile-request,api-standard-profile-request,public-profile-url,email-address)?format=json
18:52:15.618 [http-nio-8080-exec-1] DEBUG o.p.o.p.c.OAuth20ProfileCreator - sendRequestForData.120:
				response code: 500 / response body: {
  "errorCode": 0,
  "message": "Internal API server error",
  "requestId": "4YR6HUGN8M",
  "status": 500,
  "timestamp": 1550496134750
}
18:52:15.626 [http-nio-8080-exec-1] WARN  c.m.e.GlobalExceptionHandlerController - handleException.60:
				Exception
org.pac4j.core.exception.HttpCommunicationException: Failed to retrieve data / failed code : 500 and body : {
  "errorCode": 0,
  "message": "Internal API server error",
  "requestId": "4YR6HUGN8M",
  "status": 500,
  "timestamp": 1550496134750
}
	at org.pac4j.oauth.profile.creator.OAuthProfileCreator.sendRequestForData(OAuthProfileCreator.java:122)
	at org.pac4j.oauth.profile.creator.OAuthProfileCreator.retrieveUserProfileFromToken(OAuthProfileCreator.java:85)
	at org.pac4j.oauth.profile.creator.OAuthProfileCreator.create(OAuthProfileCreator.java:60)
	at org.pac4j.oauth.profile.creator.OAuthProfileCreator.create(OAuthProfileCreator.java:33)
	at org.pac4j.core.client.BaseClient.retrieveUserProfile(BaseClient.java:113)
	at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:93)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:92)
	at org.pac4j.springframework.web.CallbackController.callback(CallbackController.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

**Comment by leleuj** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
