### ISSUE TITLE
Repair SAML SP metadata signature

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1269]
See https://github.com/pac4j/pac4j/pull/1256#issuecomment-462653183

**Comment by mmoayyed** [comment]
Could you add a bit more context here? what is the issue with metadata signature?

**Comment by mmoayyed** [comment]
Running the `test-3x` branch, I see:

```
pac4j test 04:02:08 [main] ERROR n.s.t.x.XMLSecTool - Unknown error
org.cryptacular.EncodingException: Key encoding error
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.decode(AbstractPrivateKeyDecoder.java:31)
	at org.cryptacular.util.KeyPairUtil.decodePrivateKey(KeyPairUtil.java:411)
	at org.cryptacular.util.KeyPairUtil.decodePrivateKey(KeyPairUtil.java:376)
	at org.opensaml.security.crypto.KeySupport.decodePrivateKey(KeySupport.java:249)
	at org.opensaml.security.crypto.KeySupport.decodePrivateKey(KeySupport.java:202)
	at net.shibboleth.tool.xmlsectool.CredentialHelper.getFileBasedCredentials(CredentialHelper.java:79)
	at net.shibboleth.tool.xmlsectool.XMLSecTool.getCredential(XMLSecTool.java:889)
	at net.shibboleth.tool.xmlsectool.XMLSecTool.main(XMLSecTool.java:148)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.writeServiceProviderMetadataToResource(SAML2ServiceProviderMetadataResolver.java:155)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.prepareServiceProviderMetadata(SAML2ServiceProviderMetadataResolver.java:110)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.resolve(SAML2ServiceProviderMetadataResolver.java:164)
	at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolverTest.resolveServiceProviderMetadata(SAML2ServiceProviderMetadataResolverTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: java.nio.BufferOverflowException: null
		at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapCharBuffer.put(HeapCharBuffer.java:169)
	at org.cryptacular.util.PemUtil.decode(PemUtil.java:117)
	at org.cryptacular.util.PemUtil.decode(PemUtil.java:90)
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.tryConvertPem(AbstractPrivateKeyDecoder.java:47)
	at org.cryptacular.asn.AbstractPrivateKeyDecoder.decode(AbstractPrivateKeyDecoder.java:25)
	... 37 common frames omitted
```

Looking into this.

**Comment by mmoayyed** [comment]
Our method of writing key/pem files is wrong. It should be more like this:

```java
private static void writeEncodedCertificateToFile(final File file, final byte[] certificate) {
        if (file.exists()) {
            final boolean res = file.delete();
            LOGGER.debug("Deleted file [{}]:{}", file, res);
        }
        try (final PemWriter pemWriter = new PemWriter(new OutputStreamWriter(new FileOutputStream(file)))) {
            final PemObject pemObject = new PemObject(file.getName(), certificate);
            pemWriter.writeObject(pemObject);
        } catch (final Exception e) {
            LOGGER.error(e.getMessage(), e);
        }
}
```

With this, and running `clean test`, all tests pass. Pushed changes to the same branch.

**Comment by leleuj** [comment]
Excellent! I ported the fix forward.
