### ISSUE TITLE
IllegalAccessError: tried to access field org.pac4j.core.profile.Color.red from class org.pac4j.core.profile.ColorAccAccess

### ISSUE THREAD

**Issue by jknack** [pac4j/pac4j#1566]
Hi,

 Just got this error while trying to generate a JSON token.

Pac4j version: 4.0.0
Java: 1.8.0_161

Stacktrace:

```
java.lang.IllegalAccessError: tried to access field org.pac4j.core.profile.Color.red from class org.pac4j.core.profile.ColorAccAccess
	at org.pac4j.core.profile.ColorAccAccess.get(Unknown Source)
	at net.minidev.json.reader.BeansWriterASM.writeJSONString(BeansWriterASM.java:21)
	at net.minidev.json.JSONValue.writeJSONString(JSONValue.java:586)
	at net.minidev.json.reader.JsonWriter.writeJSONKV(JsonWriter.java:392)
	at net.minidev.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:145)
	at net.minidev.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:1)
	at net.minidev.json.JSONObject.writeJSON(JSONObject.java:186)
	at net.minidev.json.JSONObject.toJSONString(JSONObject.java:74)
	at net.minidev.json.JSONObject.toString(JSONObject.java:272)
	at com.nimbusds.jose.Payload.toString(Payload.java:386)
	at com.nimbusds.jose.Payload.toBytes(Payload.java:418)
	at com.nimbusds.jose.Payload.toBase64URL(Payload.java:434)
	at com.nimbusds.jose.JWSObject.<init>(JWSObject.java:121)
	at com.nimbusds.jwt.SignedJWT.<init>(SignedJWT.java:57)
	at org.pac4j.jwt.config.signature.SecretSignatureConfiguration.sign(SecretSignatureConfiguration.java:69)
	at org.pac4j.jwt.profile.JwtGenerator.internalGenerate(JwtGenerator.java:86)
	at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:71)
```

**Comment by leleuj** [comment]
What's this `ColorAccAccess`? It's not in the pac4j library.

**Comment by jknack** [comment]
Didn't realize class is not present, but the stacktrace is exactly as I posted it.

I did login with twitterclient and then try to generate a JWT token from TwitterProfile. Probably there is a bug in the `minidev.json` library, previous line seems to be using ASM to generate byte code:
`net.minidev.json.reader.BeansWriterASM.writeJSONString(BeansWriterASM.java:21)`

**Comment by leleuj** [comment]
OK. I was able to reproduce the issue and fix it by adding the appropriate setters: https://github.com/pac4j/pac4j/commit/27a406fb168148740fec1f34ed8c31bf7abfa6d8
