### ISSUE TITLE
org.pac4j.oidc.profile.creator.TokenValidator.validate method cannot return the most important error

### ISSUE THREAD

**Issue by cdmikechen** [pac4j/pac4j#1688]
I use pac4j-oidc(3.8.3) lib in apache druid by keycloak. When I login druid router, druid return error:
```
org.pac4j.core.exception.TechnicalException: com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:138)
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:40)
	at org.pac4j.core.client.BaseClient.retrieveUserProfile(BaseClient.java:113)
	at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:93)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:92)
	at org.apache.druid.security.pac4j.Pac4jFilter.doFilter(Pac4jFilter.java:94)
	at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:740)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```
I checked my oidc configuration in druid and confirm that keycloak has no configuration errors first. Then I checked pac4j codes and found that `org.pac4j.oidc.profile.creator.TokenValidator.validate` method is not very rigorous in dealing with exception returns.

For example, I add some codes in this function:
```java
public IDTokenClaimsSet validate(final JWT idToken, final Nonce expectedNonce)
        throws BadJOSEException, JOSEException {

        BadJOSEException badJOSEException = null;
        JOSEException joseException = null;

        logger.debug("check idTokenValidators {} for idToken {} with header {}",
            idTokenValidators.stream().map(idTokenValidator ->
                ((JWSVerificationKeySelector) idTokenValidator.getJWSKeySelector())
                    .getExpectedJWSAlgorithm()).collect(Collectors.toList()),
            idToken.getParsedString(), idToken.getHeader());

        for (final IDTokenValidator idTokenValidator : idTokenValidators) {

            JWSAlgorithm jwsAlgorithm = ((JWSVerificationKeySelector) idTokenValidator.getJWSKeySelector())
                .getExpectedJWSAlgorithm();
            try {
                return idTokenValidator.validate(idToken, expectedNonce);
            } catch (final BadJOSEException e1) {
                logger.debug("deal alg_name {} failed with BadJOSEException {}", jwsAlgorithm, e1);
                badJOSEException = e1;
            } catch (final JOSEException e2) {
                e2.printStackTrace();
                logger.debug("deal alg_name {} failed with JOSEException {}", jwsAlgorithm, e2);
                joseException = e2;
            }
        }

        if (badJOSEException != null) {
            throw badJOSEException;
        } else if (joseException != null) {
            throw joseException;
        } else {
            throw new TechnicalException("Unable to validate the ID token");
        }
    }
```
When I login druid again and check logs, druid logs show this error:
```
2020-09-09T00:37:07,819 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - check idTokenValidators [PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512] for idToken *** with header {"kid":"*** ","typ":"JWT","alg":"RS256"}
2020-09-09T00:37:07,852 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name PS384 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,853 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name ES384 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,853 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name RS384 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,853 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name HS256 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,854 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name HS512 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,854 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name ES256 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,880 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name RS256 failed with BadJOSEException com.nimbusds.jwt.proc.BadJWTException: JWT issue time ahead of current time
2020-09-09T00:37:07,881 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name HS384 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,881 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name ES512 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,881 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name PS256 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,882 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name PS512 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,882 DEBUG [qtp2101082331-173] org.pac4j.oidc.profile.creator.TokenValidator - deal alg_name RS512 failed with BadJOSEException com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
2020-09-09T00:37:07,882 DEBUG [qtp2101082331-173] org.eclipse.jetty.server.session - FinalSession=null old_session_manager=null this=org.eclipse.jetty.server.session.SessionHandler1057778492==dftMaxIdleSec=-1
2020-09-09T00:37:07,883 WARN [qtp2101082331-173] org.eclipse.jetty.server.HttpChannel - /druid-ext/druid-pac4j/callback
org.pac4j.core.exception.TechnicalException: com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:138) ~[?:?]
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:40) ~[?:?]
	at org.pac4j.core.client.BaseClient.retrieveUserProfile(BaseClient.java:113) ~[?:?]
	at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:93) ~[?:?]
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:92) ~[?:?]
	at org.apache.druid.security.pac4j.Pac4jFilter.doFilter(Pac4jFilter.java:94) ~[?:?]
	at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59) ~[druid-server-0.18.1.jar:0.18.1]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) ~[druid-server-0.18.1.jar:0.18.1]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:740) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.handle(Server.java:503) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.<clinit>(DefaultJWTProcessor.java:99) ~[?:?]
	at com.nimbusds.openid.connect.sdk.validators.IDTokenValidator.validate(IDTokenValidator.java:285) ~[?:?]
	at com.nimbusds.openid.connect.sdk.validators.IDTokenValidator.validate(IDTokenValidator.java:224) ~[?:?]
	at org.pac4j.oidc.profile.creator.TokenValidator.validate(TokenValidator.java:109) ~[?:?]
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:91) ~[?:?]
	... 41 more
```
I used RS256 in id_token and **deal alg_name RS256 failed with BadJOSEException com.nimbusds.jwt.proc.BadJWTException: JWT issue time ahead of current time** is the most important problem, but I got a return that wasn't what I want to return.
I think we should reconsider the actual situation of these two exceptions (`BadJOSEException` and `JoseException`) and the priority order of return or redesign, so that an exception can include multiple exception situations.

**Comment by leleuj** [comment]
I just added more logs: https://github.com/pac4j/pac4j/commit/6f9a23148d5e4caad45c1bc9d8de4f9c091d163e
