### ISSUE TITLE
java.lang.ClassCastException : net.shibboleth.utilities.java.support.resolver.CriteriaSet cannot be cast to net.shibboleth.utilities.java.support.resolver.CriteriaSet

### ISSUE THREAD

**Issue by hboumedane** [pac4j/pac4j#206]
I'm trying to use pac4j-saml 1.8.0-SNAPSHOT and I'm getting this exception :   
```java
java.lang.ClassCastException: net.shibboleth.utilities.java.support.resolver.CriteriaSet cannot be cast to net.shibboleth.utilities.java.support.resolver.CriteriaSet
	at org.opensaml.security.credential.impl.AbstractCredentialResolver.resolveSingle(AbstractCredentialResolver.java:32) ~[na:na]
	at org.pac4j.saml.crypto.KeyStoreCredentialProvider.getCredential(KeyStoreCredentialProvider.java:99) ~[na:na]
	at org.pac4j.saml.crypto.KeyStoreDecryptionProvider.build(KeyStoreDecryptionProvider.java:56) ~[na:na]
	at org.pac4j.saml.client.SAML2Client.initDecrypter(SAML2Client.java:193) ~[na:na]
	at org.pac4j.saml.client.SAML2Client.internalInit(SAML2Client.java:123) ~[na:na]
	at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:37) ~[na:na]
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:106) ~[na:na]
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:85) ~[na:na]

```

any idea about this exception ?

**Comment by leleuj** [comment]
Very strange! Both classes look the same. Maybe @mmoayyed has an idea as he developed the new SAML support...

**Comment by hboumedane** [comment]
You can close this, it's due to osgi context.
this class was loaded twice in my osgi context

**Comment by leleuj** [comment]
OK. Thx.
