### ISSUE TITLE
Concurrency issue in SAML2IdentityProviderMetadataResolver

### ISSUE THREAD

**Issue by jayaramsankara** [pac4j/pac4j#290]
I am building a SAML SP using pac4j and in the load tests, found that whenever  saml2client is shared across requests , the following exception is intermittently seen in the logs.

net.shibboleth.utilities.java.support.component.UninitializedComponentException: Component 'org.opensaml.saml.metadata.resolver.impl.DOMMetadataResolver' has not yet been initialized and cannot be used.

at net.shibboleth.utilities.java.support.component.ComponentSupport.ifNotInitializedThrowUninitializedComponentException(ComponentSupport.java:106)

at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.resolveSingle(AbstractMetadataResolver.java:164)

at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.resolveSingle(AbstractMetadataResolver.java:62)

at org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolver.getEntityDescriptorElement(SAML2IdentityProviderMetadataResolver.java:171)

at org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolver.getEntityId(SAML2IdentityProviderMetadataResolver.java:143)

at org.pac4j.saml.context.SAML2ContextProvider.addContext(SAML2ContextProvider.java:143)

at org.pac4j.saml.context.SAML2ContextProvider.addIDPContext(SAML2ContextProvider.java:134)

at org.pac4j.saml.context.SAML2ContextProvider.buildContext(SAML2ContextProvider.java:97)

at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:247)

at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:76)

at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:187)

On looking at the possible reason, I built a local version of pac4j-saml, by making the field idpMetadataProvider, a local var in the resolve method.

My tests show that this resolves the issue seen and concurrent requests for SAML request generation / assertion processing works fine.

**Comment by jayaramsankara** [comment]
Here is the commit id in my fork : https://github.com/jayaramsankara/pac4j/commit/751402f9acec1bfbaf1873cf970622c9c341c0a9

**Comment by leleuj** [comment]
Thanks for reporting.
Indeed, it seems to strange to initialize the object property: `idpMetadataProvider` in each call to the `resolve` method.
Would you mind pushing a PR?

@mmoayyed : what do you think?

**Comment by mmoayyed** [comment]
Yes, definitely. A local var sounds much better. I am not sure if the client is meant to be threadsafe, is it? And why are you calling the resolve method on every request? Shouldnt that only happen once during init?

**Comment by leleuj** [comment]
Yes, the client is meant to be thread-safe, you should have only one SAML 2 client.

**Comment by jayaramsankara** [comment]
Thanks.  Shall I send a PR with the change?

**Comment by mmoayyed** [comment]
Of course. All help is welcome :)
