### ISSUE TITLE
pac4j-saml: Typecast error in SAML2DefaultResponseValidator

### ISSUE THREAD

**Issue by jkacer** [pac4j/pac4j#306]
There is a typecast error in SAML2DefaultResponseValidator.validateAssertionSignature().
Look at the following lines:
```java
     final QName role = selfContext.getRole();
        if (signature != null) {
            final String entityId = peerContext.getEntityId();
            validateSignature(signature, entityId, engine);
        } else if (((SPSSODescriptor) role).getWantAssertionsSigned()
                && !peerContext.isAuthenticated()) {
            throw new SAMLException("Assertion or response must be signed");
        }
```
The cast of role to SPSSODescriptor is not valid. Role is of type QName and QName does not have any common part of hierarchy with SPSSODescriptor.

Once the execution gets to the else-if condition (if the signature is null), this code will crash. This stacktrace is from 1.7.1 but valid for 1.8.x too:
```
Caused by: java.lang.ClassCastException: javax.xml.namespace.QName cannot be cast to org.opensaml.saml.saml2.metadata.SPSSODescriptor
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertionSignature(SAML2DefaultResponseValidator.java:659)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertion(SAML2DefaultResponseValidator.java:400)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:307)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:151)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:83)
	at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:54)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:253)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:77)
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:222)
	at org.jasig.cas.support.pac4j.web.flow.ClientAction.doExecute(ClientAction.java:196)
	at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188) 
	at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51) 
	... 50 common frames omitted 
```

I only have limited knowledge of OpenSaml but I think we should first find a RoleDescriptor for the QName and then call getWantAssertionsSigned() on it.

**Comment by leleuj** [comment]
Hi,

Thanks for reporting this issue on the SAML support. Would you mind opening
a new Github issue for that?

I planned to release the version 1.8.0 this Thursday, I hope we'll be able
to fix that quickly.

Thanks.
Best regards,
Jérôme


2015-10-06 17:59 GMT+02:00 Jaroslav KAČER <notifications@github.com>:

**Comment by jkacer** [comment]
Hi Jerome, but this is a GitHub issue, isn't it? :-)

**Comment by leleuj** [comment]
Sorry. Yes, it is ;-)

**Comment by mmoayyed** [comment]
Working on this today. Stay tuned.

**Comment by jkacer** [comment]
Hi, I have submitted a PR that should fix the NPE thrown from the else-if condition:
https://github.com/pac4j/pac4j/pull/316

It's not crashing anymore.

HOWEVER, I'm not completely sure the code in the else branch is actually useful. In my test case (CAS against Shibboleth, assertion signing switched off), the SP Descriptor read from the SAML2MessageContext is null. Does this make sense? I think the original purpose of this code was to read the SP Descriptor (non-null) and get the WantAssertionsSigned flag from it, then throw an exception if the requirement is not fulfilled.

**Comment by leleuj** [comment]
Many thanks. Looping @mmoayyed 

If Misagh is ok, I'll merge this today, retest tonight and release (yes !) tomorrow.

**Comment by mmoayyed** [comment]
> the SP Descriptor read from the SAML2MessageContext is null. Does this make sense?

No it doesn't. I am OK with the null check, but I don't think that ever should be null. Can you investigate why that context happens to be null? You should always have the SP Descriptor.

**Comment by jkacer** [comment]
I will investigate later when I have more time...
Unless it's initialized by OpenSaml, I usually get lost there.

**Comment by mmoayyed** [comment]
I think the PR generally is fine, but if you have a null context, you might have other issues with the integration. So definitely need to look into that.

**Comment by leleuj** [comment]
@mmoayyed : can I merge and release? And investigation results on this point will be handled in version 1.8.x?

**Comment by mmoayyed** [comment]
Yes, that's the plan. I think one additional change that would go into 1.8.x is to throw exceptions when that context is null because that should not really happen, but what we have now is perfectly safe for the release, so fire away :)

**Comment by leleuj** [comment]
@jkacer : feel free to open a new issue for the "null context" issue and mark it for 1.8.1.

Many thanks again for your help.

**Comment by jkacer** [comment]
Sure, I will when I find something relevant.
And you're welcome :-)
