### ISSUE TITLE
JWT  "Illegal key size"

### ISSUE THREAD

**Issue by gschrader** [pac4j/pac4j#355]
I was trying to use the JwtGenerator however I'm getting an exception, even running the pac4j jwt unit tests I get the same exception:

```
Running org.pac4j.jwt.JwtTests
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.573 sec <<< FAILURE!
testGenerateAuthenticate(org.pac4j.jwt.JwtTests)  Time elapsed: 0.538 sec  <<< ERROR!
org.pac4j.core.exception.TechnicalException: Cannot generate JWT
	at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:91)
	at org.pac4j.jwt.JwtTests.testGenerateAuthenticate(JwtTests.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.nimbusds.jose.JOSEException: Couldn't create AES/GCM/NoPadding cipher: Illegal key size
	at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:93)
	at com.nimbusds.jose.crypto.ContentCryptoProvider.encrypt(ContentCryptoProvider.java:169)
	at com.nimbusds.jose.crypto.DirectEncrypter.encrypt(DirectEncrypter.java:118)
	at com.nimbusds.jose.JWEObject.encrypt(JWEObject.java:350)
	at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:85)
	... 30 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:89)
	... 34 more


Results :

Tests in error: 
  testGenerateAuthenticate(org.pac4j.jwt.JwtTests): Cannot generate JWT

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
```

Any ideas what is going on?

**Comment by gschrader** [comment]
I thought maybe it was a JDK thing, tried latest u65 on macosx and windows with the same exception.

**Comment by leleuj** [comment]
You need: "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files" if you don't have already installed them: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by gschrader** [comment]
Thank you that did the trick, is there a way to make it fall back to the limited policy files? Or is that a bad idea?

**Comment by gschrader** [comment]
I'm also not able to get the generated token to decode in my javascript, or pasting it in the debugger at http://jwt.io

**Comment by gschrader** [comment]
Ok I think I'm starting to understand better, the website and probably the js library only supports HS256 where as pac4j is generating the token with A256GCM.

**Comment by gschrader** [comment]
I'm just confusing myself the more I look. It looks like the payload is encrypted with A256GCM. Is there an example outside of the unit test to have a look at?

**Comment by leleuj** [comment]
Currently, the idea with the JWT support is to not let people decide what they want for encryption (it does both: encryption to protect the data of the user profile and hashing).
The `JwtGenerator` and `JwtAuthenticator` are fairly clear in their implementations and it should not be difficult to provide ways to change encryption/hashing methods to meet your needs.
Feel free to submit a pull request for that (some appropriate setters should do the job + documentation).

**Comment by leleuj** [comment]
Please use the mailing list for any questions.
