### ISSUE TITLE
Bad JWS signature

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#371]
When login at Google using the OpenID Connect protocol, I get the following error:

```
org.pac4j.core.exception.TechnicalException: com.nimbusds.jose.JOSEException: Bad JWS signature
        at org.pac4j.oidc.client.OidcClient.retrieveUserProfile(OidcClient.java:369)
        at org.pac4j.oidc.client.OidcClient.retrieveUserProfile(OidcClient.java:88)
        at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:99)
        at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:48)
        at org.pac4j.j2e.filter.CallbackFilter.internalFilter(CallbackFilter.java:85)
        at org.pac4j.j2e.filter.AbstractConfigFilter.doFilter(AbstractConfigFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1113)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1047)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:238)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:57)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.nimbusds.jose.JOSEException: Bad JWS signature
        at com.nimbusds.openid.connect.sdk.util.DefaultJWTDecoder.verify(DefaultJWTDecoder.java:158)
        at com.nimbusds.openid.connect.sdk.util.DefaultJWTDecoder.decodeJWT(DefaultJWTDecoder.java:217)
        at org.pac4j.oidc.client.OidcClient.retrieveUserProfile(OidcClient.java:351)
        ... 29 more
```

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/384

Updated oauth-oidc-sdk to version 5.0-alpha13 and nimbus-jose-jwt to version 4.9

**Comment by leleuj** [comment]
Reopened to use the IDTokenVerifier: https://github.com/pac4j/pac4j/pull/385

**Comment by leleuj** [comment]
Fixing time issue and improving `OidcClient`:  https://github.com/pac4j/pac4j/pull/388
