### ISSUE TITLE
Store null values as empty strings

### ISSUE THREAD

**Issue by PR-O** [pac4j/pac4j#424]
This is a request to store null values as empty strings, as Redis (the cache store we use) does not support null values.

**Comment by mmoayyed** [comment]
May I ask, what do you use Redis for?

**Comment by PR-O** [comment]
Sure. We use Redis as a global Cache store.

**Comment by PR-O** [comment]
I've forked the latest pac4j to do the corrections and offer a PR, but it seems 4 out of 8 pac4j for JWT tests are failing, each yielding an InvalidKeyException (before making any changes):

testGenerateAuthenticate(org.pac4j.jwt.JwtTests)  Time elapsed: 0.676 sec  <<< ERROR!
        org.pac4j.core.exception.TechnicalException: Cannot generate JWT
                at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:135)
                at org.pac4j.jwt.JwtTests.testGenerateAuthenticate(JwtTests.java:75)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:497)
                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
                at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:497)
                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
        Caused by: com.nimbusds.jose.JOSEException: Couldn't create AES/GCM/NoPadding cipher: Illegal key size
                at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:93)
                at com.nimbusds.jose.crypto.ContentCryptoProvider.encrypt(ContentCryptoProvider.java:169)
                at com.nimbusds.jose.crypto.DirectEncrypter.encrypt(DirectEncrypter.java:118)
                at com.nimbusds.jose.JWEObject.encrypt(JWEObject.java:353)
                at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:127)
                ... 30 more
        Caused by: java.security.InvalidKeyException: Illegal key size
                at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
                at javax.crypto.Cipher.implInit(Cipher.java:805)
                at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
                at javax.crypto.Cipher.init(Cipher.java:1396)
                at javax.crypto.Cipher.init(Cipher.java:1327)
                at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:89)
                ... 34 more

**Comment by mmoayyed** [comment]
Understood :) I was asking, how is the cache store related to what you do with pac4j?

**Comment by mmoayyed** [comment]
PS Not saying we shouldnt support this request obviously. I am just curious!

**Comment by PR-O** [comment]
Well, Pac4J stores various objects in cache. Because we're using Redis for caching, pac4j has stopped working after upgrading from 1.7.x to 1.8.x.

**Comment by leleuj** [comment]
@PR-O : I see your problem, builds are ok at Travis: https://travis-ci.org/pac4j/pac4j/builds and locally for me.
You certainly need this extension for Java to fully support encryption: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by PR-O** [comment]
Weird.. It seems I have those installed already. Never mind, I will offer a PR since my changes don't seem to break any more tests.

**Comment by PR-O** [comment]
#425

**Comment by PR-O** [comment]
Any idea/ETA when this will be released? We have made a lot of changes surrounding the pac4j 1.8.x upgrade, and we can't continue without this.

**Comment by leleuj** [comment]
Did you re-test successfullly with pac4j v1.8.3-SNAPSHOT? I had no specific ETA in mind, it can be done when it's necessary for you.

**Comment by PR-O** [comment]
@leleuj , just tested this with 1.8.3-SNAPSHOT. Works like a charm! Concerning the release: whenever you're ready :smile: .

**Comment by leleuj** [comment]
I think it will come soon (next week). I'm looking forward to start version 1.9...

**Comment by leleuj** [comment]
Notice I did this fix on your patch: https://github.com/pac4j/pac4j/commit/ad96f73c20ae64d1d2adc1c9f70998c54fedee67

**Comment by fastf0rward** [comment]
Perfect. Are you still planning on releasing 1.8.3 this week? If so, I will adjust our release path accordingly :smile: .

**Comment by leleuj** [comment]
pac4j v1.8.3 and play-pac4j v2.0.1 have been released!

**Comment by fastf0rward** [comment]
Great news! Nice work @leleuj !
