### ISSUE TITLE
pac4j-saml has incompatible OpenSAML v2 dependency on xmltooling

### ISSUE THREAD

**Issue by jhegg** [pac4j/pac4j#444]
Hello,

I recently [opened an issue against OpenSAML v3](https://issues.shibboleth.net/jira/browse/OSJ-152), where I was getting the following stacktrace:

```
Caused by: java.lang.ClassCastException: org.opensaml.xml.schema.impl.XSAnyBuilder cannot be cast to org.opensaml.core.xml.XMLObjectBuilder
	at org.opensaml.core.xml.config.XMLConfigurator.initializeObjectProviders(XMLConfigurator.java:238)
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:203)
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:188)
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:162)
	at org.opensaml.core.xml.config.AbstractXMLObjectProviderInitializer.init(AbstractXMLObjectProviderInitializer.java:52)
	at org.opensaml.core.xml.config.XMLObjectProviderInitializer.init(XMLObjectProviderInitializer.java:45)
	at org.opensaml.core.config.InitializationService.initialize(InitializationService.java:56)
	at org.pac4j.saml.util.Configuration.bootstrap(Configuration.java:76)
	at org.pac4j.saml.util.Configuration.<clinit>(Configuration.java:49)
	... 8 more
```

The error is due to having conflicting jar resources at the same path (two jars have the same resource file in the same path, such as default-config.xml), so I presumed that it was an OpenSAML issue that only showed up if the classloader ordered jars in a specific way. However, [according to the response to my issue](https://issues.shibboleth.net/jira/browse/OSJ-152?focusedCommentId=22022&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22022), xmltooling is part of OpenSAML v2, and is not intended nor tested alongside OpenSAML v3.

The [pac4j-saml pom.xml has an explicit dependency on xmltooling](https://github.com/pac4j/pac4j/blob/6b090ac1bb466ca038de9ae20a44284da636d289/pac4j-saml/pom.xml#L166-L168), so it appears that needs to be removed. Is there any specific reason that xmltooling is an explicit dependency of pac4j-saml?

Note that when I remove the dependency of pac4j-saml on xmltooling, that leads to two classes getting NoClassDefFoundError on `org/opensaml/xml/util/XMLHelper`: `org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolver` and `org.pac4j.saml.metadata.SAML2MetadataGenerator`. They both appear to be using XMLHelper#nodeToString, and it appears that the method has moved in OpenSAML v3 to `net.shibboleth.utilities.java.support.xml.SerializeSupport` (with the same signature and javadoc) contained in the `net.shibboleth.utilities:java-support:7.1.1` transitive dependency of opensaml-core. So, unless I missed something, it may be a quick fix.

**Comment by jhegg** [comment]
I might have a fix ready, although I still need to test it in my environment that exhibited the problem (caused by the classloader ordering). If I submit a PR, should I target the 1.8.x branch, or master? If it works out, it would be very helpful for me if it were released soon, as I'm hoping to use this in production soon. I'm sure everyone says that! :smile:
