### ISSUE TITLE
NullPointer in DOMMetadataResolver

### ISSUE THREAD

**Issue by saschak094** [pac4j/pac4j#544]
Hi, 

I am developing a undertow pac4j application and I have the following problem. 

I am working with the SAML2ClientConfiguration like in the undertow-pac4j demo application and passing the values like this: 

`final SAML2ClientConfiguration cfg = new SAML2ClientConfiguration("resource:samlKeystore.jks",
				"pac4j-demo-passwd", "pac4j-demo-passwd",
				"file:path_to_id.xml");`

In eclipse it works fine without errors, but building the application and starting via command line doesn't work. On the command line I get the following exception: 

java.lang.NullPointerException: null
	at org.opensaml.saml.metadata.resolver.impl.DOMMetadataResolver.initMetadataResolver(DOMMetadataResolver.java:68) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.doInitialize(AbstractMetadataResolver.java:191) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at net.shibboleth.utilities.java.support.component.AbstractInitializableComponent.initialize(AbstractInitializableComponent.java:61) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.saml.metadata.SAML2IdentityProviderMetadataResolver.resolve(SAML2IdentityProviderMetadataResolver.java:114) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.saml.client.SAML2Client.initIdentityProviderMetadataResolver(SAML2Client.java:181) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.saml.client.SAML2Client.internalInit(SAML2Client.java:124) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.core.util.InitializableWebObject.init(InitializableWebObject.java:39) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:123) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:85) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.undertow.SecurityMechanism.redirectToIdentityProvider(SecurityMechanism.java:208) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.pac4j.undertow.SecurityMechanism.sendChallenge(SecurityMechanism.java:178) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.impl.SecurityContextImpl$ChallengeSender.transition(SecurityContextImpl.java:283) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.impl.SecurityContextImpl$ChallengeSender.access$300(SecurityContextImpl.java:266) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.impl.SecurityContextImpl.sendChallenges(SecurityContextImpl.java:125) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:104) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:89) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.handlers.AuthenticationCallHandler.handleRequest(AuthenticationCallHandler.java:50) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793) ~[undertow-pac4j-demo-1.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]

It seems that the Unmarshaller are not registered while running the application on the command line. 
Can you provide help ?

**Comment by leleuj** [comment]
Very strange. I just tested it via command line or through IntelliJ and it works. Can you try a `mvn -X`?

**Comment by saschak094** [comment]
The maven build looks fine also with -X

**Comment by leleuj** [comment]
I see version `1.3.0-SNAPSHOT` while the demo is currently in version `1.1.0-SNAPSHOT`: did you change something? Does it work with the default demo?

**Comment by saschak094** [comment]
It works now seems that the maven assembly plugin is not supported

**Comment by leleuj** [comment]
OK. Good to know.
