### ISSUE TITLE
NoSuchMethodError org.pac4j.core.client.Client.redirect(Lorg/pac4j/core/context/WebContext;ZZ)V

### ISSUE THREAD

**Issue by sharmapankaj2512** [pac4j/pac4j#594]
Hi,

I am trying to setup basic authentication using following dependencies

compile 'org.pac4j:spark-pac4j:1.0.3'
compile 'org.pac4j:pac4j-http:1.8.8'
 compile 'org.pac4j:pac4j-sql:1.8.0'

On get request to a protected url I got below shown exception.

java.lang.NoSuchMethodError: org.pac4j.core.client.Client.redirect(Lorg/pac4j/core/context/WebContext;ZZ)V
	at org.pac4j.sparkjava.RequiresAuthenticationFilter.handle(RequiresAuthenticationFilter.java:68)
	at spark.FilterImpl$1.handle(FilterImpl.java:62)
	at spark.http.matching.BeforeFilters.execute(BeforeFilters.java:48)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:125)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

Thanks in advance  for the help :)

**Comment by sharmapankaj2512** [comment]
I was using incompatible versions of spark-pack4j and pack4j-http.  This was a false alarm.

**Comment by sharmapankaj2512** [comment]
Although I would like to know, is there a compatibility matrix for these modules?

**Comment by leleuj** [comment]
spark-pac4j v1.0.3 has a dependency on pac4j v1.7, so you can use any **1.7.x** pac4j version: 1.7.0, 1.7.1 or 1.7.2.

spark-pac4j v1.1.x has a dependency on pac4j v1.8, so you can use any **1.8.x** version: 1.8.0, 1.8.1... 1.8.9

spark-pac4j v1.2 will have a dependency on pac4j v1.9.

This is explained in the README, in the "Dependencies" section.
