### ISSUE TITLE
Name cannot be blank SAMLv2

### ISSUE THREAD

**Issue by tpraizler** [pac4j/pac4j#784]
Hi, 

I use:
```
  "org.pac4j" % "play-pac4j" % "2.6.1",
  "org.pac4j" % "pac4j-saml" % "1.9.4"
```

Here is the security module code: 

```
class SecurityModule(environment: Environment, configuration: Configuration) extends AbstractModule {

  override def configure(): Unit = {
    val cfg = new SAML2ClientConfiguration()
    cfg.setMaximumAuthenticationLifetime(3600)
    cfg.setServiceProviderEntityId("https://app.my-app-name.com/saml")
    cfg.setIdentityProviderEntityId("http://www.okta.com/some_id")      
    cfg.setIdentityProviderMetadataPath("https://my-app-name.oktapreview.com/app/some_id/sso/saml/metadata")

    val saml2Client = new SAML2Client(cfg)
    val clients = new Clients("https://localhost:9443/api/oktaCallback", saml2Client)

    val config = new Config(clients)
    config.setHttpActionAdapter(new DemoHttpActionAdapter())
    bind(classOf[Config]).toInstance(config)

    bind(classOf[PlaySessionStore]).to(classOf[PlayCacheStore])

    // callback
    val callbackController = new CallbackController()
    callbackController.setDefaultUrl("/")
    callbackController.setMultiProfile(true)
    bind(classOf[CallbackController]).toInstance(callbackController)
  }
}

class DemoHttpActionAdapter extends DefaultHttpActionAdapter {

  override def adapt(code: Int, context: PlayWebContext): Result = {
    if (code == HttpConstants.UNAUTHORIZED) {
      Results.unauthorized("unauthorized").as(HttpConstants.HTML_CONTENT_TYPE)
    } else if (code == HttpConstants.FORBIDDEN) {
      Results.forbidden("forbidden").as(HttpConstants.HTML_CONTENT_TYPE)
    } else {
      super.adapt(code, context)
    }
  }
}
```

My routes:
```
GET           /api/oktaLogin                                                          com.myapp.security.saml.SamlController.oktaLogin
GET           /api/oktaCallback                                                       org.pac4j.play.CallbackController.callback()
POST          /api/oktaCallback                                                       org.pac4j.play.CallbackController.callback()
```

Controller code:
```
class SamlController @Inject()(val playSessionStore: PlaySessionStore,
                               override val ec: HttpExecutionContext,
                               val config: Config)
  extends Controller with Security[CommonProfile]{

  def oktaLogin() = Action { implicit request =>
    val context: PlayWebContext = new PlayWebContext(request, playSessionStore)
    val client = config.getClients.findClient(context.getRequestParameter(Clients.DEFAULT_CLIENT_NAME_PARAMETER)).asInstanceOf[IndirectClient[Credentials,CommonProfile]]
   Redirect("https://okta-sso-url")
  }

  def oktaCallback = Secure("SAML2Client") { profiles =>
    Action { request =>
      Ok
    }
  }
}
```

The problem is in the callback flow, I get this exception:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: org.pac4j.core.exception.TechnicalException: name cannot be blank]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at com.my-app-name.filters.ErrorHandler.onServerError(ErrorHandler.scala:40)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.CompletionException: org.pac4j.core.exception.TechnicalException: name cannot be blank
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	... 6 common frames omitted
Caused by: org.pac4j.core.exception.TechnicalException: name cannot be blank
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:134)
	at org.pac4j.core.util.CommonHelper.assertNotBlank(CommonHelper.java:145)
	at org.pac4j.core.client.Clients.findClient(Clients.java:131)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:70)
	at org.pac4j.play.CallbackController.lambda$callback$3(CallbackController.java:50)
	at org.pac4j.play.CallbackController$$Lambda$52/1539159182.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	... 7 common frames omitted

```

Any idea?

**Comment by leleuj** [comment]
You don't need to perform the computation and redirection explicitly, this is done by the `Secure` function and above all, the `Secure` function should be used to protect URLs and not for the `oktaCallback` method which must remain non-authenticated.

**Comment by leleuj** [comment]
See: https://github.com/pac4j/play-pac4j#3a-protect-urls-per-action-secure and https://github.com/pac4j/play-pac4j#4-define-the-callback-endpoint-only-for-indirect-clients-callbackcontroller

**Comment by tpraizler** [comment]
Oh I see thanks! @leleuj 
So in my case I don't need to use the `Secure` method.

I only need a login url which will redirect to okta, and a callback url that will parse the saml configuration coming from okta. 
At the end of the day I need the saml parsing and to get the email of the user.
all my apis are protected with a different machism (I wish I used this one instead at the beginning) 

So how do I do that? the callbackcontroller is invoked by using the secure method, but I don't need it.

Is there a way to achieve what I need?

**Comment by leleuj** [comment]
The `Secure("SAML2Client")` function will trigger the redirection to Okta and after a successful authentication, you'll be redirected to the originally requested URL.

```scala
def oktaIndex = Secure("SAML2Client") { profiles =>
 Action { request =>
   // here you have the SAML authenticated profile of the user
 }
}
```

You need the `CallbackController` in all cases, whether the redirection was triggered "manually" or by the `Secure` function. 

You should use the default callback controller: `GET    /api/oktaCallback    @org.pac4j.play.CallbackController.callback()`

**Comment by tpraizler** [comment]
Thank you for your help!

So you are saying that when hit a `Secure` end point, the user will be redirected to okta, authenticate, and will be redirected back to the app.
But where do I configure the SSO url to which the client will  be redirected to okta? I couldn't find it in the `SAML2ClientConfiguration`.

**Comment by leleuj** [comment]
Here is the configuration we use (in another pac4j implementation) to use SAML login with Okta: https://github.com/pac4j/spring-security-pac4j-demo/blob/master/src/main/resources/securityContext.xml#L202

This information is in the Okta metadata you have uploaded and referenced locally: https://github.com/pac4j/spring-security-pac4j-demo/blob/master/src/main/resources/metadata-okta.xml

**Comment by tpraizler** [comment]
@leleuj I think I understand how it should work now:) That's great!

So I configured when trying to hit to oktaIndex endpoint which is configured with the Secured, everything should heppen based on the provided metadata. cool.

So now when I hit this end point I get:

`[CompletionException: org.pac4j.core.exception.TechnicalException: Either keyStore, keyStoreResource or keyStorePath must be provided]`

I didn't configure the keystore. do I have to? we already have a certificate provided by go daddy, which mean that hour connection is secured. Did I miss anything?

**Comment by tpraizler** [comment]
OK! it worked when I defined the demo keystore.
I followed the instructions in the [saml configuration page](http://www.pac4j.org/docs/clients/saml.html).
And created a keystore using the following command:
`keytool -genkeypair -alias pac4j-demo -keypass pac4j-demo-passwd -keystore samlKeystore.jks -storepass pac4j-demo-passwd -keyalg RSA -keysize 2048 -validity 3650`

The thing is I am not sure what should I do when I reales it to prodcution.
Why should I define a keystore? if I must could I use this one?

**Comment by leleuj** [comment]
The security of the SAML protocol relies on the fact that assertions are encrypted. The keystore stores the key used for encryption.

**Comment by tpraizler** [comment]
@leleuj Thanks!
But if I am not doing any assertion, but only redirect the user to okta, okta redirect him (after authentication) back. why do I need to encrypt anything?
Sorry for the nooby questions..:(

But I am trying to understand what I am missing. what do I need to encrypt in this case?
BTW, if I must use some kind of keystore, do I need to configure it in okta also?

Thanks again for your patience.

**Comment by leleuj** [comment]
Encryption is part of the SAML protocol.

**Comment by tpraizler** [comment]
I see. thanks! @leleuj 
So I will need to have a keystore file protected by password. I will do that.

The [saml documentation](http://www.pac4j.org/docs/clients/saml.html) says: "Alternatively, you can also let pac4j create the keystore for you. If the keystore resource path does not exist, pac4j will attempt to generate a keystore and produce the relevant key pairs inside it."

How is this possible? Is it a safe option?

**Comment by leleuj** [comment]
Yes, the keystore is automatically created if it does not exist and you must use a relative or absolute path file.

**Comment by tpraizler** [comment]
This is great. @leleuj 

I tried it like this:

```
cfg.setKeystorePath(environment.getFile("conf").getAbsolutePath + "/samlKeystore.jks") 
//cfg.setKeystorePath("conf/samlKeystore.jks") this also didn't work 
cfg.setKeystorePassword("my-password")
cfg.setPrivateKeyPassword("my-password")
```

But it failed, looks like the keystore file was not created. I get : 

`[CompletionException: org.pac4j.core.exception.TechnicalException: java.io.FileNotFoundException: /fullpath-to-may-app/conf/samlKeystore.jks (No such file or directory)]`

What am I missing?
Thanks again for your help.

**Comment by tpraizler** [comment]
I found the problem. I looked on the SamlConfiguration code, and it seems the creation of the keystore is not part of the empty constructor flow.

I add to use a different constructor: 
```
val cfg = new SAML2ClientConfiguration(
      environment.getFile("conf").getAbsolutePath + "/samlKeystore.jks",
      keyStorePassword,
      keyStorePassword,
      oktaMetadata)
```

In such case (empty constructor) it would be nice to have this method exposed, so one can invoke it after setting all the relevant parameters.
