### ISSUE TITLE
JwtProfile expects audience claim to always be a string

### ISSUE THREAD

**Issue by pm-pasi-harme** [pac4j/pac4j#801]
I am using jax-rs-pac4j 1.0.0 with pac4j 1.9.5 and I use Jackson for serializing the response entities. Given the following JAX-RS resource:

```
@Path("/profile")
@Pac4JSecurity(clients = "HeaderClient", authorizers = "isAuthenticated")
public class UserProfileResource {
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getUserData(@Pac4JProfile JwtProfile profile) {
        return Response.ok(profile).build();
    }
}
```

When I make a GET request to this endpoint, a ClassCastException is thrown when JwtProfile tries to cast the audience claim into a string. In my case the claim is an array of strings which is valid [according to the RFC spec](https://tools.ietf.org/html/rfc7519#section-4.1.3).

Here is the stack trace:
```
com.fasterxml.jackson.databind.JsonMappingException: java.util.Arrays$ArrayList cannot be cast to java.lang.String (through reference chain: org.pac4j.jwt.profile.JwtProfile["audience"])
	... 
Caused by: java.lang.ClassCastException: java.util.Arrays$ArrayList cannot be cast to java.lang.String
	at org.pac4j.jwt.profile.JwtProfile.getAudience(JwtProfile.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:664)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	... 53 common frames omitted
```

**Comment by leleuj** [comment]
Yes, the same problem exist in the `OidcProfile`:  https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/profile/OidcProfile.java#L87

Would you mind submitting a PR to fix both?

**Comment by leleuj** [comment]
@pm-pasi-harme Proposed fix: https://github.com/pac4j/pac4j/pull/824
