### ISSUE TITLE
Upgrade to Scribe v4 (OAuth support)

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#860]

**Comment by jhusson** [comment]
Salut Jérome,

I got this exception with facebook oauth API

```
Caused by: org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from this: '{"access_token":"EAAIrRZBcZBxEsBAGWdBsRCgiMkOsha5HHPOiUdIeSsnbobhNT96zGeG3jHUZCgZADZAXLAE1c1cmEQZCOtfwjfgSkiySb571P3EY4aXTxUq86yAZCQGpv6vqOxZBi2AhHdqpiRggmfeaBmZBmtceVORmvADriWjXDxd0egzM4nsjOwgZDZD","token_type":"bearer","expires_in":5181341}'
	at org.scribe.extractors.TokenExtractor20Impl.extract(TokenExtractor20Impl.java:33)
	at org.scribe.oauth.ProxyOAuth20ServiceImpl.getAccessToken(ProxyOAuth20ServiceImpl.java:65)
	at org.pac4j.oauth.client.BaseOAuth20Client.getAccessToken(BaseOAuth20Client.java:106)
	at org.pac4j.oauth.client.BaseOAuthClient.retrieveUserProfile(BaseOAuthClient.java:163)
```

The Api changed the version number to v2.8 and the return value from the API is now in JSON-Format and no longer escaped in the URI. Seems old 'scribe' packages can not handle this changes.

Maybe upgrade to scribe v4 can resolve this problem.

**Comment by leleuj** [comment]
I just tested a demo with the 2.0.0-RC3-SNAPSHOT version and I have no issue with Facebook. How do get this problem?

Upgrading to Scribe v4 is a big task I want to avoid so close from the deadline of the v2.
