### ISSUE TITLE
According to the official demo configuration, pac4j-shiro, why does this error occur all the time? Configure it several times and ask for help. Thank you!

### ISSUE THREAD

**Issue by xfwangpf** [pac4j/pac4j#973]
2017-08-12 16:33:16.479 ERROR 5444 --- [io-18080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filtered request failed.] with root cause

org.pac4j.core.exception.TechnicalException: name cannot be blank
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:134) ~[pac4j-core-1.9.7.jar:na]
	at org.pac4j.core.util.CommonHelper.assertNotBlank(CommonHelper.java:145) ~[pac4j-core-1.9.7.jar:na]
	at org.pac4j.core.client.Clients.findClient(Clients.java:141) ~[pac4j-core-1.9.7.jar:na]
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:70) ~[pac4j-core-1.9.7.jar:na]
	at io.buji.pac4j.filter.CallbackFilter.doFilter(CallbackFilter.java:74) ~[buji-pac4j-2.2.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at io.buji.pac4j.filter.SecurityFilter.lambda$doFilter$0(SecurityFilter.java:80) ~[buji-pac4j-2.2.0.jar:na]
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:139) ~[pac4j-core-1.9.7.jar:na]
	at io.buji.pac4j.filter.SecurityFilter.doFilter(SecurityFilter.java:78) ~[buji-pac4j-2.2.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112) ~[shiro-web-1.4.0.jar:1.4.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) ~[shiro-web-1.4.0.jar:1.4.0]
	at io.buji.pac4j.filter.SecurityFilter.lambda$doFilter$0(SecurityFilter.java:80) ~[buji-pac4j-2.2.0.jar:na]
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:139) ~[pac4j-core-1.9.7.jar:na]
	at io.buji.pac4j.filter.SecurityFilter.doFilter(SecurityFilter.java:78) ~[buji-pac4j-2.2.0.jar:na]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[shiro-web-1.4.0.jar:1.4.0]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) ~[shiro-web-1.4.0.jar:1.4.0]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) ~[shiro-web-1.4.0.jar:1.4.0]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) ~[shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) ~[shiro-web-1.4.0.jar:1.4.0]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) ~[shiro-web-1.4.0.jar:1.4.0]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.5.jar:8.5.5]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]

**Comment by xfwangpf** [comment]
CAS service is validated, but this error occurs when you jump to client，Here is my configuration file。
@Bean
	public CasClient casClient(){
		CasClient casClient = new CasClient();
		casClient.setCasLoginUrl("https://cas.xfwang.com:8443/cas/login");
		//casClient.setCallbackUrl("http://app:18080/callback");
		return casClient;
	}
	@Bean 
	public Clients Clients(){
		Clients clients = new Clients();
		clients.setClients(casClient());
		clients.setCallbackUrl("http://app:18080/callback");
		return clients;
	}
	@Bean
	public RequireAnyRoleAuthorizer requireAnyRoleAuthorizer(){
		RequireAnyRoleAuthorizer requireAnyRoleAuthorizer = new RequireAnyRoleAuthorizer();
		requireAnyRoleAuthorizer.setElements("ROLE_ADMIN");
		return requireAnyRoleAuthorizer;
	}
	@Bean
	public CustomAuthorizer customAuthorizer(){
		CustomAuthorizer customAuthorizer = new CustomAuthorizer();
		return customAuthorizer;
	}
	@Bean
	public ExcludedPathMatcher excludedPathMatcher(){
		return new ExcludedPathMatcher();
	}
	@Bean Config config(){
		Config  config = new Config();
		
		config.setClients(Clients());
		return config;
	}
	@Bean
	public SecurityFilter securityFilter(){
		SecurityFilter securityFilter = new SecurityFilter();
		securityFilter.setConfig(config());
		securityFilter.setClients("CasClient");
		return securityFilter;
	}
	@Bean
	public CallbackFilter callbackFilter(){
		CallbackFilter callbackFilter = new CallbackFilter();
		callbackFilter.setConfig(config());
		callbackFilter.setMultiProfile(true);
		return callbackFilter;
	}

**Comment by xfwangpf** [comment]
CAS service validation successful, jump to client is an error，Here is my configuration file。
@Bean
	public CasClient casClient(){
		CasClient casClient = new CasClient();
		casClient.setCasLoginUrl("https://cas.xfwang.com:8443/cas/login");
		//casClient.setCallbackUrl("http://app:18080/callback");
		return casClient;
	}
	@Bean 
	public Clients Clients(){
		Clients clients = new Clients();
		clients.setClients(casClient());
		clients.setCallbackUrl("http://app:18080/callback");
		return clients;
	}
@Bean Config config(){
		Config  config = new Config();
		
		config.setClients(Clients());
		return config;
	}
	@Bean
	public SecurityFilter securityFilter(){
		SecurityFilter securityFilter = new SecurityFilter();
		securityFilter.setConfig(config());
		securityFilter.setClients("CasClient");
		return securityFilter;
	}
	@Bean
	public CallbackFilter callbackFilter(){
		CallbackFilter callbackFilter = new CallbackFilter();
		callbackFilter.setConfig(config());
		callbackFilter.setMultiProfile(true);
		return callbackFilter;
	}

**Comment by leleuj** [comment]
Please use the pac4j-users mailing list: http://www.pac4j.org/mailing-lists.html
